title: Unip Warehouse
payoff: Believe in Design
email: abdurrahman.alhanif@gmail.com
greet: Hello!
description: >
  I'm Hanif, a freelance Frontend Dev, UI/UX Designer and illustrator from Sleman, Yogyakarta
baseurl: ""
url: "https://unipwarehouse.github.io"
logo: "/img/logo-horizontal.svg"
logo_small: "/img/logo-icon.svg"

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - resources
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  posts:
    permalink: /posts/:categories/:title
  works:
    defaults:
      type: work
      layout: work
    permalink: /works/:categories/:title
    output: true

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      type: "post"
  -
    scope:
      type: "works"
    values:
      layout: "work"
      type: "work"

sass:
  style: compressed
